version: "3.0"
services:
  db-postgres-event:
    image: postgres:alpine
    ports:
      - "5435:5432"
    container_name: "db-postgres-event"
    restart: always
    volumes:
      - ./database-forum-api:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
  app-forum-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-forum-api
    ports:
      - "3000:3000"
    volumes:
      - ./app-forum-api/app
    links:
      - db-postgres-event
    depends_on:
      - db-postgres-event

volumes:
  db-postgres-event:
